services:
  python_env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyenv_python_3_13_dev
    volumes:
      - .:/app  # Mount the current directory to the /app directory in the container
    working_dir: /app
    stdin_open: true  # Keep stdin open for interactive mode
    tty: true         # Allocate a pseudo-TTY
